name: hello

on:
  workflow_dispatch:
    inputs:
      word:
        description: ''
        required: true
        default: 'World'

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, ${{ github.event.inputs.word }}."