name: say

on:
  workflow_dispatch:
    inputs:
      say_input:
        description: ''
        required: true
        default: 'Hello!!'

jobs:
  say_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "say. ( ^o^)<${{ github.event.inputs.say_input }}"