name: say2

on:
  workflow_dispatch:
    inputs:
      say_input:
        description: ''
        required: true
        default: 'Hello!!'

jobs:
  say2_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "say2. ( ^o^)<${{ github.event.inputs.say_input }}"